import java.util.*;

public class ArrayListJava {

    public static void main(String[] args) {

            Scanner sc = new Scanner(System.in);

                    // 1. Create ArrayList
                            ArrayList<Integer> list = new ArrayList<>();

                                    // 2. Add elements
                                            System.out.print("Enter number of elements: ");
                                                    int n = sc.nextInt();

                                                            System.out.println("Enter elements:");
                                                                    for (int i = 0; i < n; i++) {
                                                                                list.add(sc.nextInt());
                                                                                        }

                                                                                                System.out.println("ArrayList: " + list);

                                                                                                        // 3. Get element
                                                                                                                if (!list.isEmpty()) {
                                                                                                                            System.out.println("First element: " + list.get(0));
                                                                                                                                    }

                                                                                                                                            // 4. Set (update element)
                                                                                                                                                    if (!list.isEmpty()) {
                                                                                                                                                                list.set(0, 100);
                                                                                                                                                                            System.out.println("After updating first element to 100: " + list);
                                                                                                                                                                                    }

                                                                                                                                                                                            // 5. Remove element
                                                                                                                                                                                                    if (!list.isEmpty()) {
                                                                                                                                                                                                                list.remove(0);
                                                                                                                                                                                                                            System.out.println("After removing first element: " + list);
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                            // 6. Size of list
                                                                                                                                                                                                                                                    System.out.println("Size: " + list.size());

                                                                                                                                                                                                                                                            // 7. Check if contains element
                                                                                                                                                                                                                                                                    System.out.print("Enter element to search: ");
                                                                                                                                                                                                                                                                            int key = sc.nextInt();

                                                                                                                                                                                                                                                                                    if (list.contains(key)) {
                                                                                                                                                                                                                                                                                                System.out.println("Element found!");
                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                    System.out.println("Element not found!");
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                    // 8. Iterate ArrayList
                                                                                                                                                                                                                                                                                                                                            System.out.print("Elements using loop: ");
                                                                                                                                                                                                                                                                                                                                                    for (int i = 0; i < list.size(); i++) {
                                                                                                                                                                                                                                                                                                                                                                System.out.print(list.get(i) + " ");
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                System.out.println();

                                                                                                                                                                                                                                                                                                                                                                                        // 9. Sort ArrayList
                                                                                                                                                                                                                                                                                                                                                                                                Collections.sort(list);
                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Sorted ArrayList: " + list);

                                                                                                                                                                                                                                                                                                                                                                                                                // 10. Reverse ArrayList
                                                                                                                                                                                                                                                                                                                                                                                                                        Collections.reverse(list);
                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("Reversed ArrayList: " + list);

                                                                                                                                                                                                                                                                                                                                                                                                                                        // 11. Find max and min
                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!list.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Max: " + Collections.max(list));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Min: " + Collections.min(list));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sc.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }