import java.util.*;

public class LinkedListJava {

    public static void main(String[] args) {

            Scanner sc = new Scanner(System.in);

                    // 1. Create LinkedList
                            LinkedList<Integer> list = new LinkedList<>();

                                    // 2. Add elements
                                            System.out.print("Enter number of elements: ");
                                                    int n = sc.nextInt();

                                                            System.out.println("Enter elements:");
                                                                    for (int i = 0; i < n; i++) {
                                                                                list.add(sc.nextInt());
                                                                                        }

                                                                                                System.out.println("LinkedList: " + list);

                                                                                                        // 3. Add at first and last
                                                                                                                list.addFirst(10);
                                                                                                                        list.addLast(20);
                                                                                                                                System.out.println("After addFirst & addLast: " + list);

                                                                                                                                        // 4. Get elements
                                                                                                                                                if (!list.isEmpty()) {
                                                                                                                                                            System.out.println("First element: " + list.getFirst());
                                                                                                                                                                        System.out.println("Last element: " + list.getLast());
                                                                                                                                                                                }

                                                                                                                                                                                        // 5. Remove elements
                                                                                                                                                                                                if (!list.isEmpty()) {
                                                                                                                                                                                                            list.removeFirst();
                                                                                                                                                                                                                        list.removeLast();
                                                                                                                                                                                                                                    System.out.println("After removeFirst & removeLast: " + list);
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                    // 6. Size
                                                                                                                                                                                                                                                            System.out.println("Size: " + list.size());

                                                                                                                                                                                                                                                                    // 7. Check contains
                                                                                                                                                                                                                                                                            System.out.print("Enter element to search: ");
                                                                                                                                                                                                                                                                                    int key = sc.nextInt();

                                                                                                                                                                                                                                                                                            if (list.contains(key)) {
                                                                                                                                                                                                                                                                                                        System.out.println("Element found!");
                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                            System.out.println("Element not found!");
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                            // 8. Iterate LinkedList
                                                                                                                                                                                                                                                                                                                                                    System.out.print("Elements using loop: ");
                                                                                                                                                                                                                                                                                                                                                            for (int i = 0; i < list.size(); i++) {
                                                                                                                                                                                                                                                                                                                                                                        System.out.print(list.get(i) + " ");
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                        System.out.println();

                                                                                                                                                                                                                                                                                                                                                                                                // 9. Reverse LinkedList
                                                                                                                                                                                                                                                                                                                                                                                                        Collections.reverse(list);
                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("Reversed LinkedList: " + list);

                                                                                                                                                                                                                                                                                                                                                                                                                        // 10. Sort LinkedList
                                                                                                                                                                                                                                                                                                                                                                                                                                Collections.sort(list);
                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Sorted LinkedList: " + list);

                                                                                                                                                                                                                                                                                                                                                                                                                                                // 11. Peek & Poll (Queue behavior)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Peek (head): " + list.peek());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("Poll (remove head): " + list.poll());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("After poll: " + list);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sc.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }